"""empty message

Revision ID: 8b653eeb2828
Revises: 7ac252f2bbbf
Create Date: 2023-03-28 21:25:25.879073

"""

# revision identifiers, used by Alembic.
revision = '8b653eeb2828'
down_revision = '7ac252f2bbbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('outgoing_only', sa.Boolean(), nullable=True))
    op.alter_column('user', 'spam_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'80.'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'spam_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'80.'"))
    op.drop_column('domain', 'outgoing_only')
    # ### end Alembic commands ###
